"""Exercise name -> muscle group, for server-side volume reporting.

GENERATED FILE — do not edit by hand.
Source: Vaux/Vaux/Services/ExerciseCatalog.swift
Regenerate: python tools/generate_muscle_map.py
"""

MUSCLE_GROUPS: dict[str, str] = {
    "45 degree leg press": "Legs",
    "ab rollout": "Abs",
    "ab wheel": "Abs",
    "abductor": "Legs",
    "adductor": "Legs",
    "arnold press": "Shoulders",
    "back extension": "Back",
    "barbell curl": "Biceps",
    "barbell row": "Back",
    "bench press": "Chest",
    "bent over row": "Back",
    "bent-over row": "Back",
    "bicep": "Biceps",
    "bicep curl": "Biceps",
    "biceps curl": "Biceps",
    "cable crossover": "Chest",
    "cable crunch": "Abs",
    "cable curl": "Biceps",
    "cable fly": "Chest",
    "cable overhead extension": "Triceps",
    "cable row": "Back",
    "calf": "Calves",
    "calf press": "Calves",
    "calf raise": "Calves",
    "calf raises": "Calves",
    "calves": "Calves",
    "chest fly": "Chest",
    "chest press": "Chest",
    "chest supported row": "Back",
    "chest-supported row": "Back",
    "chin up": "Back",
    "chin-up": "Back",
    "chin-ups": "Back",
    "chinup": "Back",
    "close grip bench": "Triceps",
    "close-grip bench": "Triceps",
    "concentration curl": "Biceps",
    "crunch": "Abs",
    "crunches": "Abs",
    "curl": "Biceps",
    "db row": "Back",
    "dead bug": "Abs",
    "deadlift": "Back",
    "decline press": "Chest",
    "dips": "Chest",
    "donkey calf": "Calves",
    "dumbbell curl": "Biceps",
    "dumbbell row": "Back",
    "ez bar curl": "Biceps",
    "ez-bar curl": "Biceps",
    "face pull": "Rear Delts",
    "face pulls": "Rear Delts",
    "front raise": "Shoulders",
    "glute bridge": "Legs",
    "glute kickback": "Legs",
    "good morning": "Legs",
    "hammer curl": "Biceps",
    "hamstring curl": "Legs",
    "high row": "Back",
    "hip abduction": "Legs",
    "hip adduction": "Legs",
    "hip thrust": "Legs",
    "hollow hold": "Abs",
    "horizontal leg press": "Legs",
    "incline barbell press": "Chest",
    "incline bench": "Chest",
    "incline chest press": "Chest",
    "incline curl": "Biceps",
    "incline db press": "Chest",
    "incline dumbbell press": "Chest",
    "incline machine press": "Chest",
    "incline press": "Chest",
    "inverted row": "Back",
    "kickback": "Triceps",
    "knee raise": "Abs",
    "lat pulldown": "Back",
    "lateral raise": "Shoulders",
    "lateral raises": "Shoulders",
    "leg curl": "Legs",
    "leg curls": "Legs",
    "leg extension": "Legs",
    "leg press": "Legs",
    "leg raise": "Abs",
    "leg raises": "Abs",
    "low row": "Back",
    "lunge": "Legs",
    "lunges": "Legs",
    "lying leg curl": "Legs",
    "machine row": "Back",
    "military press": "Shoulders",
    "mountain climber": "Abs",
    "nordic curl": "Legs",
    "overhead cable extension": "Triceps",
    "overhead extension": "Triceps",
    "overhead press": "Shoulders",
    "overhead tricep": "Triceps",
    "overhead triceps": "Triceps",
    "pallof press": "Abs",
    "pec deck": "Chest",
    "pec fly": "Chest",
    "pendlay row": "Back",
    "plank": "Abs",
    "preacher curl": "Biceps",
    "pull up": "Back",
    "pull ups": "Back",
    "pull-up": "Back",
    "pull-ups": "Back",
    "pulldown": "Back",
    "pullup": "Back",
    "pullups": "Back",
    "push press": "Shoulders",
    "push up": "Chest",
    "push ups": "Chest",
    "push-down": "Triceps",
    "push-up": "Chest",
    "push-ups": "Chest",
    "pushdown": "Triceps",
    "pushup": "Chest",
    "pushups": "Chest",
    "rack pull": "Back",
    "rdl": "Legs",
    "rear delt": "Rear Delts",
    "rear delt fly": "Rear Delts",
    "rear delt raise": "Rear Delts",
    "reverse cable fly": "Rear Delts",
    "reverse fly": "Rear Delts",
    "reverse pec deck": "Rear Delts",
    "rollout": "Abs",
    "romanian deadlift": "Legs",
    "rope extension": "Triceps",
    "rope pushdown": "Triceps",
    "russian twist": "Abs",
    "seated calf": "Calves",
    "seated leg curl": "Legs",
    "seated row": "Back",
    "shoulder press": "Shoulders",
    "shrug": "Back",
    "shrugs": "Back",
    "side raise": "Shoulders",
    "single leg press": "Legs",
    "single-leg press": "Legs",
    "sit up": "Abs",
    "sit-up": "Abs",
    "sit-ups": "Abs",
    "situp": "Abs",
    "skull crusher": "Triceps",
    "skull crushers": "Triceps",
    "skullcrusher": "Triceps",
    "spider curl": "Biceps",
    "squat": "Legs",
    "standing calf": "Calves",
    "step up": "Legs",
    "step-up": "Legs",
    "step-ups": "Legs",
    "stiff leg deadlift": "Legs",
    "stiff-leg deadlift": "Legs",
    "sumo leg press": "Legs",
    "sumo press": "Legs",
    "t bar row": "Back",
    "t-bar row": "Back",
    "toe press": "Calves",
    "tricep": "Triceps",
    "tricep dip": "Triceps",
    "tricep extension": "Triceps",
    "tricep pushdown": "Triceps",
    "triceps extension": "Triceps",
    "triceps pushdown": "Triceps",
    "unilateral leg press": "Legs",
    "upright row": "Shoulders",
    "vertical leg press": "Legs",
}

BODYWEIGHT_MOVEMENTS: tuple[str, ...] = (
    "ab wheel",
    "chin up",
    "chin-up",
    "chinup",
    "dip",
    "hanging knee raise",
    "hanging leg raise",
    "hollow hold",
    "inverted row",
    "knee raise",
    "leg raise",
    "muscle up",
    "muscle-up",
    "nordic curl",
    "plank",
    "pull up",
    "pull-up",
    "pullup",
    "push up",
    "push-up",
    "pushup",
    "rollout",
)

# Fractional volume attribution. Prime mover 1.0, heavily-involved
# synergist 0.5, minor 0.25. Used ONLY for volume counting — strength
# trends deliberately keep single (prime-mover) attribution.
MUSCLE_CONTRIBUTIONS: dict[str, dict[str, float]] = {
    "barbell row": {"Back": 1.0, "Biceps": 0.5, "Rear Delts": 0.5},
    "bench press": {"Chest": 1.0, "Shoulders": 0.5, "Triceps": 0.5},
    "cable row": {"Back": 1.0, "Biceps": 0.5, "Rear Delts": 0.5},
    "chest press": {"Chest": 1.0, "Shoulders": 0.5, "Triceps": 0.5},
    "chin-up": {"Back": 1.0, "Biceps": 0.5},
    "db row": {"Back": 1.0, "Biceps": 0.5, "Rear Delts": 0.5},
    "decline press": {"Chest": 1.0, "Triceps": 0.5},
    "dips": {"Chest": 1.0, "Triceps": 0.5},
    "dumbbell row": {"Back": 1.0, "Biceps": 0.5, "Rear Delts": 0.5},
    "hack squat": {"Hamstrings": 0.25, "Quads": 1.0},
    "incline barbell press": {"Chest": 1.0, "Shoulders": 0.5, "Triceps": 0.5},
    "incline bench": {"Chest": 1.0, "Shoulders": 0.5, "Triceps": 0.5},
    "incline chest press": {"Chest": 1.0, "Shoulders": 0.5, "Triceps": 0.5},
    "incline db press": {"Chest": 1.0, "Shoulders": 0.5, "Triceps": 0.5},
    "incline dumbbell press": {"Chest": 1.0, "Shoulders": 0.5, "Triceps": 0.5},
    "incline machine press": {"Chest": 1.0, "Shoulders": 0.5, "Triceps": 0.5},
    "incline press": {"Chest": 1.0, "Shoulders": 0.5, "Triceps": 0.5},
    "lat pulldown": {"Back": 1.0, "Biceps": 0.5},
    "leg curl": {"Hamstrings": 1.0},
    "leg extension": {"Quads": 1.0},
    "leg press": {"Hamstrings": 0.25, "Quads": 1.0},
    "machine row": {"Back": 1.0, "Biceps": 0.5, "Rear Delts": 0.5},
    "overhead press": {"Shoulders": 1.0, "Triceps": 0.5},
    "pull-up": {"Back": 1.0, "Biceps": 0.5},
    "pulldown": {"Back": 1.0, "Biceps": 0.5},
    "pullup": {"Back": 1.0, "Biceps": 0.5},
    "romanian deadlift": {"Back": 0.5, "Hamstrings": 1.0},
    "seated row": {"Back": 1.0, "Biceps": 0.5, "Rear Delts": 0.5},
    "shoulder press": {"Shoulders": 1.0, "Triceps": 0.5},
    "squat": {"Hamstrings": 0.25, "Quads": 1.0},
    "sumo press": {"Hamstrings": 0.25, "Quads": 1.0},
    "t-bar row": {"Back": 1.0, "Biceps": 0.5, "Rear Delts": 0.5},
}
